include: package:lint/analysis_options_package.yaml
linter:
    rules:
        non_constant_identifier_names: false
      #constant_identifier_names: false
analyzer:
    exclude:
      #- lib/**.gr.dart
      #- lib/**.g.dart
      #- lib/**.freezed.dart    