name: flutter_vision_scanner
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  freezed_annotation:
  json_annotation:
  lint: ^1.0.0
  ios_platform_images: ^0.1.2+2
dependency_overrides:
  analyzer: '0.39.14'  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.11.5
  json_serializable: ^3.2.0
  

flutter:
  plugin:
    platforms:
      android:
        package: de.spielgestalt.flutter_vision_scanner
        pluginClass: FlutterVisionScannerPlugin
      ios:
        pluginClass: FlutterVisionScannerPlugin